language: objective-c
cache: cocoapods
xcode_workspace: Cortado/Cortado.xcworkspace
xcode_scheme: Cortado
xcode_sdk: iphonesimulator

before_install:
  - gem install cocoapods cocoapods-keys --no-ri --no-rdoc
  - gem install slather --no-ri --no-rdoc

after_success: slather